version: '3.4'

services:
  imlistening:
    image: ${DOCKER_REGISTRY-}imlistening
    build:
      context: .
      dockerfile: ImListening/Dockerfile
    networks:
      - localnet
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: Microsoft.AspNetCore.SpaProxy
    ports:
      - '8081:44428'

  mongodb:
    image: mongo:latest
    ports:
      - '27019:27017'
    networks:
      - localnet
      
networks:
  localnet:
    attachable: true

