version: '3.4'

services:
  imlistening:
    image: imlistening
    container_name: imlistening
    build:
      context: .
      dockerfile: ImListening/Dockerfile
    networks:
      - localnet
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: Microsoft.AspNetCore.SpaProxy
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
    ports:
      - '8081:44428'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: imlisteningmongo
    ports:
      - '27019:27017'
    networks:
      - localnet
      
networks:
  localnet:
    attachable: true

