version: '3.4'

services:
  imlistening:
    image: imlistening
    container_name: imlistening
    build:
      context: .
      dockerfile: ImListening/Dockerfile
    networks:
      - localnet
    environment:
      MONGO_DB_CONNECTION_STRING: mongodb://host.docker.internal:27019
      DATABASE_NAME: WebHooks

    ports:
      - '8081:44428'
      - '8082:443'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: imlisteningmongo
    ports:
      - '27019:27017'
    networks:
      - localnet
      
networks:
  localnet:
    attachable: true

